rabbitmq:
  image: rafakato/rabbitmq-delayed-message-exchange:3.6.1-management
  ports:
    - "5672:5672"
    - "15672:15672"
mosquitto:
  image: eclipse-mosquitto
  ports:
    - "1883:1883"
redis:
  image: redis
  ports:
    - "6379:6379"